<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tag;

/**
 * @property mixed $tag_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 * @property null|\Atlas\Mapper\DataSource\Tagging\TaggingRecordSet $taggings
 */
trait TagFields
{
}
