<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tag;

use Atlas\Table\Row;

/**
 * @property mixed $tag_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 */
class TagRow extends Row
{
    protected mixed $tag_id = null;
    protected mixed $name = null;
}
