<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Thread;

use Atlas\Table\Table;

/**
 * @method ThreadRow|null fetchRow($primaryVal)
 * @method ThreadRow[] fetchRows(array $primaryVals)
 * @method ThreadTableSelect select(array $whereEquals = [])
 * @method ThreadRow newRow(array $cols = [])
 * @method ThreadRow newSelectedRow(array $cols)
 */
class ThreadTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'threads';

    const COLUMNS = [
        'thread_id' => [
            'name' => 'thread_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'author_id' => [
            'name' => 'author_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'subject' => [
            'name' => 'subject',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'body' => [
            'name' => 'body',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'thread_id',
        'author_id',
        'subject',
        'body',
    ];

    const COLUMN_DEFAULTS = [
        'thread_id' => null,
        'author_id' => null,
        'subject' => null,
        'body' => null,
    ];

    const PRIMARY_KEY = [
        'thread_id',
    ];

    const AUTOINC_COLUMN = 'thread_id';

    const AUTOINC_SEQUENCE = null;
}
