<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Comment;

/**
 * @property mixed $comment_id INTEGER
 * @property mixed $related_type VARCHAR(255)
 * @property mixed $related_id INTEGER
 * @property mixed $body TEXT
 * @property null|false|\Atlas\Mapper\Record $commentable (variant)
 */
trait CommentFields
{
}
