<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Tagging;

use Atlas\Table\Table;

/**
 * @method TaggingRow|null fetchRow($primaryVal)
 * @method TaggingRow[] fetchRows(array $primaryVals)
 * @method TaggingTableSelect select(array $whereEquals = [])
 * @method TaggingRow newRow(array $cols = [])
 * @method TaggingRow newSelectedRow(array $cols)
 */
class TaggingTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'taggings';

    const COLUMNS = [
        'tagging_id' => [
            'name' => 'tagging_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'thread_id' => [
            'name' => 'thread_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'tag_id' => [
            'name' => 'tag_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'tagging_id',
        'thread_id',
        'tag_id',
    ];

    const COLUMN_DEFAULTS = [
        'tagging_id' => null,
        'thread_id' => null,
        'tag_id' => null,
    ];

    const PRIMARY_KEY = [
        'tagging_id',
    ];

    const AUTOINC_COLUMN = 'tagging_id';

    const AUTOINC_SEQUENCE = null;
}
