<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Student\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\CompositeDataSource\Student\StudentRecord;
use Atlas\Mapper\CompositeDataSource\Student\StudentRecordSet;

/**
 * @method ?StudentRecord fetchRecord()
 * @method StudentRecord[] fetchRecords()
 * @method StudentRecordSet fetchRecordSet()
 * @method ?StudentRow fetchRow()
 * @method StudentRow[] fetchRows()
 */
abstract class StudentSelect_ extends MapperSelect
{
}
