<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Student\_generated;

use Atlas\Table\Table;
use Atlas\Mapper\CompositeDataSource\Student\StudentRow;
use Atlas\Mapper\CompositeDataSource\Student\StudentTableSelect;

/**
 * @method ?StudentRow fetchRow(mixed $primaryVal)
 * @method StudentRow[] fetchRows(array $primaryVals)
 * @method StudentTableSelect select(array $whereEquals = [])
 * @method StudentRow newRow(array $cols = [])
 * @method StudentRow newSelectedRow(array $cols)
 */
abstract class StudentTable_ extends Table
{
    public const DRIVER = 'sqlite';

    public const NAME = 'students';

    public const COLUMNS = [
        'student_fn' => [
            'name' => 'student_fn',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'student_ln' => [
            'name' => 'student_ln',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'degree_type' => [
            'name' => 'degree_type',
            'type' => 'CHAR',
            'size' => 2,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'degree_subject' => [
            'name' => 'degree_subject',
            'type' => 'CHAR',
            'size' => 4,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    public const PRIMARY_KEY = [
        'student_fn',
        'student_ln',    ];

    public const COMPOSITE_KEY = true;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = StudentRow::CLASS;
}
