<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Student\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\CompositeDataSource\Student\StudentRecord;
use Atlas\Mapper\CompositeDataSource\Student\StudentRecordSet;
use Atlas\Mapper\CompositeDataSource\Student\StudentRelated;
use Atlas\Mapper\CompositeDataSource\Student\StudentSelect;
use Atlas\Mapper\CompositeDataSource\Student\StudentTable;

/**
 * @method StudentTable getTable()
 * @method ?StudentRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?StudentRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method StudentRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method StudentRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method StudentRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method StudentRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method StudentSelect select(array $whereEquals = [])
 * @method StudentRecord newRecord(array $fields = [])
 * @method StudentRecord[] newRecords(array $fieldSets)
 * @method StudentRecordSet newRecordSet(array $records = [])
 * @method StudentRecord turnRowIntoRecord(StudentRow $row, array $loadRelated = [])
 * @method StudentRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Student_ extends Mapper
{
    public const RECORD_CLASS = StudentRecord::CLASS;
    public const RECORD_SET_CLASS = StudentRecordSet::CLASS;
    public const RELATED_CLASS = StudentRelated::CLASS;
    public const SELECT_CLASS = StudentSelect::CLASS;
}
