<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Student\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Mapper\CompositeDataSource\Student\StudentRecord;
use Atlas\Mapper\CompositeDataSource\Student\StudentRecordSet;

/**
 * @method __construct(StudentRecord[], callable $newRecordFactory)
 * @method StudentRecord offsetGet($offset)
 * @method StudentRecord appendNew(array $fields = [])
 * @method ?StudentRecord getOneBy(array $whereEquals)
 * @method StudentRecordSet getAllBy(array $whereEquals)
 * @method ?StudentRecord detachOneBy(array $whereEquals)
 * @method StudentRecordSet detachAllBy(array $whereEquals)
 * @method StudentRecordSet detachAll()
 * @method StudentRecordSet detachDeleted()
 */
abstract class StudentRecordSet_ extends RecordSet
{
}
