<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Degree;

use Atlas\Table\Table;

/**
 * @method DegreeRow|null fetchRow($primaryVal)
 * @method DegreeRow[] fetchRows(array $primaryVals)
 * @method DegreeTableSelect select(array $whereEquals = [])
 * @method DegreeRow newRow(array $cols = [])
 * @method DegreeRow newSelectedRow(array $cols)
 */
class DegreeTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'degrees';

    const COLUMNS = [
        'degree_type' => [
            'name' => 'degree_type',
            'type' => 'CHAR',
            'size' => 2,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'degree_subject' => [
            'name' => 'degree_subject',
            'type' => 'CHAR',
            'size' => 4,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'VARCHAR',
            'size' => 50,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'degree_type',
        'degree_subject',
        'title',
    ];

    const COLUMN_DEFAULTS = [
        'degree_type' => null,
        'degree_subject' => null,
        'title' => null,
    ];

    const PRIMARY_KEY = [
        'degree_type',
        'degree_subject',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
