<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Employee;

class EmployeeRow extends _generated\EmployeeRow_
{
}
