<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Employee;

/**
 * @property mixed $id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 * @property mixed $building INTEGER
 * @property mixed $floor INTEGER
 */
trait EmployeeFields
{
}
