<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Post;

/**
 * @property mixed $post_id INTEGER
 * @property mixed $subj VARCHAR(255)
 * @property mixed $body TEXT
 * @property null|\Atlas\Mapper\DataSource\Comment\CommentRecordSet $comments
 */
trait PostFields
{
}
