<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Course;

/**
 * @property mixed $course_subject CHAR(4)
 * @property mixed $course_number INT
 * @property mixed $title VARCHAR(20)
 * @property null|\Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRecordSet $enrollments
 */
trait CourseFields
{
}
