<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Student;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $degree_type CHAR(2)
 * @property mixed $degree_subject CHAR(4)
 * @property null|false|\Atlas\Mapper\CompositeDataSource\Gpa\GpaRecord $gpa
 * @property null|false|\Atlas\Mapper\CompositeDataSource\Degree\DegreeRecord $degree
 * @property null|\Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRecordSet $enrollments
 * @property null|\Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRecordSet $engl_enrollments
 */
trait StudentFields
{
}
