<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Degree\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\CompositeDataSource\Degree\DegreeRecord;
use Atlas\Mapper\CompositeDataSource\Degree\DegreeRecordSet;

/**
 * @method ?DegreeRecord fetchRecord()
 * @method DegreeRecord[] fetchRecords()
 * @method DegreeRecordSet fetchRecordSet()
 * @method ?DegreeRow fetchRow()
 * @method DegreeRow[] fetchRows()
 */
abstract class DegreeSelect_ extends MapperSelect
{
}
