<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Degree\_generated;

use Atlas\Table\TableSelect;
use Atlas\Mapper\CompositeDataSource\Degree\DegreeRow;

/**
 * @method ?DegreeRow fetchRow()
 * @method DegreeRow[] fetchRows()
 */
abstract class DegreeTableSelect_ extends TableSelect
{
}
