<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Degree\_generated;

use Atlas\Table\Table;
use Atlas\Mapper\CompositeDataSource\Degree\DegreeRow;
use Atlas\Mapper\CompositeDataSource\Degree\DegreeTableSelect;

/**
 * @method ?DegreeRow fetchRow(mixed $primaryVal)
 * @method DegreeRow[] fetchRows(array $primaryVals)
 * @method DegreeTableSelect select(array $whereEquals = [])
 * @method DegreeRow newRow(array $cols = [])
 * @method DegreeRow newSelectedRow(array $cols)
 */
abstract class DegreeTable_ extends Table
{
    public const DRIVER = 'sqlite';

    public const NAME = 'degrees';

    public const COLUMNS = [
        'degree_type' => [
            'name' => 'degree_type',
            'type' => 'CHAR',
            'size' => 2,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'degree_subject' => [
            'name' => 'degree_subject',
            'type' => 'CHAR',
            'size' => 4,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'VARCHAR',
            'size' => 50,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    public const PRIMARY_KEY = [
        'degree_type',
        'degree_subject',    ];

    public const COMPOSITE_KEY = true;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = DegreeRow::CLASS;
}
