<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Post\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $post_id INTEGER
 * @property mixed $subj VARCHAR(255)
 * @property mixed $body TEXT
 * @method \Atlas\Mapper\DataSource\Post\PostRow getRow()
 */
abstract class PostRecord_ extends Record
{
}
