<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidibar;

/**
 * @property mixed $bidibar_id INTEGER
 * @property mixed $bidifoo_id INTEGER
 * @property mixed $name VARCHAR(10)
 * @property null|false|\Atlas\Mapper\DataSource\Bidifoo\BidifooRecord $bidifoo
 */
trait BidibarFields
{
}
