<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Bidibar;

class BidibarRow extends _generated\BidibarRow_
{
}
