<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Enrollment\_generated;

use Atlas\Table\TableSelect;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRow;

/**
 * @method ?EnrollmentRow fetchRow()
 * @method EnrollmentRow[] fetchRows()
 */
abstract class EnrollmentTableSelect_ extends TableSelect
{
}
