<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Enrollment\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $course_subject CHAR(4)
 * @property mixed $course_number INT
 * @property mixed $grade INT
 * @property mixed $points INT
 * @method \Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRow getRow()
 */
abstract class EnrollmentRecord_ extends Record
{
}
