<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Enrollment\_generated;

use Atlas\Table\Table;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRow;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentTableSelect;

/**
 * @method ?EnrollmentRow fetchRow(mixed $primaryVal)
 * @method EnrollmentRow[] fetchRows(array $primaryVals)
 * @method EnrollmentTableSelect select(array $whereEquals = [])
 * @method EnrollmentRow newRow(array $cols = [])
 * @method EnrollmentRow newSelectedRow(array $cols)
 */
abstract class EnrollmentTable_ extends Table
{
    public const DRIVER = 'sqlite';

    public const NAME = 'enrollments';

    public const COLUMNS = [
        'student_fn' => [
            'name' => 'student_fn',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'student_ln' => [
            'name' => 'student_ln',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'course_subject' => [
            'name' => 'course_subject',
            'type' => 'CHAR',
            'size' => 4,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'course_number' => [
            'name' => 'course_number',
            'type' => 'INT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'grade' => [
            'name' => 'grade',
            'type' => 'INT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'points' => [
            'name' => 'points',
            'type' => 'INT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    public const PRIMARY_KEY = [
        'student_fn',
        'student_ln',
        'course_subject',
        'course_number',    ];

    public const COMPOSITE_KEY = true;

    public const AUTOINC_COLUMN = null;

    public const AUTOINC_SEQUENCE = null;

    public const ROW_CLASS = EnrollmentRow::CLASS;
}
