<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Enrollment\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRecord;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRecordSet;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRelated;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentSelect;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentTable;

/**
 * @method EnrollmentTable getTable()
 * @method ?EnrollmentRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?EnrollmentRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method EnrollmentRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method EnrollmentRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method EnrollmentRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method EnrollmentRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method EnrollmentSelect select(array $whereEquals = [])
 * @method EnrollmentRecord newRecord(array $fields = [])
 * @method EnrollmentRecord[] newRecords(array $fieldSets)
 * @method EnrollmentRecordSet newRecordSet(array $records = [])
 * @method EnrollmentRecord turnRowIntoRecord(EnrollmentRow $row, array $loadRelated = [])
 * @method EnrollmentRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Enrollment_ extends Mapper
{
    public const RECORD_CLASS = EnrollmentRecord::CLASS;
    public const RECORD_SET_CLASS = EnrollmentRecordSet::CLASS;
    public const RELATED_CLASS = EnrollmentRelated::CLASS;
    public const SELECT_CLASS = EnrollmentSelect::CLASS;
}
