<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Enrollment\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRecord;
use Atlas\Mapper\CompositeDataSource\Enrollment\EnrollmentRecordSet;

/**
 * @method ?EnrollmentRecord fetchRecord()
 * @method EnrollmentRecord[] fetchRecords()
 * @method EnrollmentRecordSet fetchRecordSet()
 * @method ?EnrollmentRow fetchRow()
 * @method EnrollmentRow[] fetchRows()
 */
abstract class EnrollmentSelect_ extends MapperSelect
{
}
