<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Video;

use Atlas\Table\Row;

/**
 * @property mixed $video_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $url VARCHAR(255)
 */
class VideoRow extends Row
{
    protected mixed $video_id = null;
    protected mixed $title = null;
    protected mixed $url = null;
}
