<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Video;

/**
 * @property mixed $video_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $url VARCHAR(255)
 * @property null|\Atlas\Mapper\DataSource\Comment\CommentRecordSet $comments
 */
trait VideoFields
{
}
