<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\DataSource\Author;

/**
 * @property mixed $author_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 * @property null|\Atlas\Mapper\DataSource\Reply\ReplyRecordSet $replies
 * @property null|\Atlas\Mapper\DataSource\Thread\ThreadRecordSet $threads
 */
trait AuthorFields
{
}
