<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Course\_generated;

use Atlas\Mapper\Related;

abstract class CourseRelated_ extends Related
{
}
