<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Course\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\CompositeDataSource\Course\CourseRecord;
use Atlas\Mapper\CompositeDataSource\Course\CourseRecordSet;

/**
 * @method ?CourseRecord fetchRecord()
 * @method CourseRecord[] fetchRecords()
 * @method CourseRecordSet fetchRecordSet()
 * @method ?CourseRow fetchRow()
 * @method CourseRow[] fetchRows()
 */
abstract class CourseSelect_ extends MapperSelect
{
}
