<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Enrollment;

use Atlas\Table\Table;

/**
 * @method EnrollmentRow|null fetchRow($primaryVal)
 * @method EnrollmentRow[] fetchRows(array $primaryVals)
 * @method EnrollmentTableSelect select(array $whereEquals = [])
 * @method EnrollmentRow newRow(array $cols = [])
 * @method EnrollmentRow newSelectedRow(array $cols)
 */
class EnrollmentTable extends Table
{
    public const ROW_CLASS = EnrollmentRow::CLASS;

    public const COMPOSITE_KEY = true;

    const DRIVER = 'sqlite';

    const NAME = 'enrollments';

    const COLUMNS = [
        'student_fn' => [
            'name' => 'student_fn',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'student_ln' => [
            'name' => 'student_ln',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'course_subject' => [
            'name' => 'course_subject',
            'type' => 'CHAR',
            'size' => 4,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'course_number' => [
            'name' => 'course_number',
            'type' => 'INT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
            'options' => null,
        ],
        'grade' => [
            'name' => 'grade',
            'type' => 'INT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'points' => [
            'name' => 'points',
            'type' => 'INT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'student_fn',
        'student_ln',
        'course_subject',
        'course_number',
        'grade',
        'points',
    ];

    const COLUMN_DEFAULTS = [
        'student_fn' => null,
        'student_ln' => null,
        'course_subject' => null,
        'course_number' => null,
        'grade' => null,
        'points' => null,
    ];

    const PRIMARY_KEY = [
        'student_fn',
        'student_ln',
        'course_subject',
        'course_number',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
