<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Gpa\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $gpa DECIMAL(4,3)
 * @method \Atlas\Mapper\CompositeDataSource\Gpa\GpaRow getRow()
 */
abstract class GpaRecord_ extends Record
{
}
