<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Gpa\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Mapper\CompositeDataSource\Gpa\GpaRecord;
use Atlas\Mapper\CompositeDataSource\Gpa\GpaRecordSet;

/**
 * @method __construct(GpaRecord[], callable $newRecordFactory)
 * @method GpaRecord offsetGet($offset)
 * @method GpaRecord appendNew(array $fields = [])
 * @method ?GpaRecord getOneBy(array $whereEquals)
 * @method GpaRecordSet getAllBy(array $whereEquals)
 * @method ?GpaRecord detachOneBy(array $whereEquals)
 * @method GpaRecordSet detachAllBy(array $whereEquals)
 * @method GpaRecordSet detachAll()
 * @method GpaRecordSet detachDeleted()
 */
abstract class GpaRecordSet_ extends RecordSet
{
}
