<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Mapper\CompositeDataSource\Gpa\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Mapper\CompositeDataSource\Gpa\GpaRecord;
use Atlas\Mapper\CompositeDataSource\Gpa\GpaRecordSet;

/**
 * @method ?GpaRecord fetchRecord()
 * @method GpaRecord[] fetchRecords()
 * @method GpaRecordSet fetchRecordSet()
 * @method ?GpaRow fetchRow()
 * @method GpaRow[] fetchRows()
 */
abstract class GpaSelect_ extends MapperSelect
{
}
